caxy/php-htmldiff

lib/Caxy/HtmlDiff/ListDiff.php

…caused a null reference to be passed.

Fix: Updated code so that null is not given in list formatting.

---

lib/Caxy/HtmlDiff/ListDiff.php

https://caxyinteractive.atlassian.net/browse/ICC-4882

Updated list diff class to maintain the tags on lists.

---

lib/Caxy/HtmlDiff/HtmlDiff.php
tests/fixtures/HtmlDiff/issue-28-link-changes.html

Feature request from #28.
I didn't go as far as adding the functionality for displaying a tooltip of the change, as that is out of the scope of this library and could be done with some post-processing / JS.
Example:
Old Text: `<a href="http://caxy.com">Test</a>`
New Text: `<a href="http://google.com">Test</a>`
Output:
```html
<del class="diffmod diff-href"><a href="http://caxy.com">Test</a></del><ins class="diffmod diff-href"><a href="http://google.com">Test</a></ins>
```

Detect link changes to resolve #28

---

composer.json
lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php
lib/Caxy/HtmlDiff/ListDiffNew.php
lib/Caxy/HtmlDiff/Table/TableDiff.php

Created a new class `Caxy\HtmlDiff\HtmlDiffConfig` to house the configuration options for HtmlDiff/ListDiff/TableDiff in an object. We've added a decent amount of config options to the HtmlDiff class, and it's getting quite messy having to pass these options individually into each new instance of ListDiff/TableDiff/HtmlDiff that we end up creating. So now we can just pass the object along!
In order to be backwards-compatible, I left the __construct intact as well as the public getter/setter functions for the config options, but I marked them as deprecated.
Use `HtmlDiff::setConfig` to set the configuration object. The __construct is currently creating a new instance of HtmlDiffConfig with the default options by default, so you don't actually need to create a new object if you don't want …

Create configuration class for HtmlDiff config options

---

composer.json
lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/DiffCache.php
lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php
lib/Caxy/HtmlDiff/ListDiffNew.php
lib/Caxy/HtmlDiff/Table/TableDiff.php

Allows setting an object that implements the `Doctrine\Common\Cache\Cache` interface on the `Caxy\HtmlDiff\HtmlDiffConfig` object. If this is set, then that cache provider will be used to cache the calculated diff contents.
Needs test coverage.

Allow caching of the calculated diffs using a doctrine cache provider

---

lib/Caxy/HtmlDiff/HtmlDiffConfig.php
lib/Caxy/HtmlDiff/Table/TableDiff.php

- Update TableDiff to initialize purifier with a cache storage location.  Without this, it defaults to the vendor folder.
- Updated the HtmlDiffConfig for the additional parameter.
I think the defaults shouldn't break anything as is.  But if there's a better way than initializing the purifier twice due to the create call I'm listening.

Update TableDiff HTMLPurifier Initialization.

---

lib/Caxy/HtmlDiff/Table/TableDiff.php

This slipped through.  ```$this``` is not correct, we should be calling the method on the new object being created.
Also had to update the method call to public from protected.

Fixed issue with create call on TableDiff object

---

demo/codes.css

Updates to demo styles for #45 
Background: This `codes.css` file was pulled in directly from a project we use this library in, and I never actually went in and cleaned it up or removed the extra pork... so doing that now.

Cleanup CSS and add styles for highlighting differences (#45)

---

lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/ListDiff.php
lib/Caxy/HtmlDiff/ListDiffLines.php
lib/Caxy/HtmlDiff/Table/TableDiff.php
tests/Caxy/Tests/HtmlDiff/Functional/HTMLPurifierConfigTest.php

Fixed HTMLPurifier not using the cache directory

---

lib/Caxy/HtmlDiff/LcsService.php
lib/Caxy/HtmlDiff/ListDiffLines.php

In php 5.3 you can not use []. This changes the two times [] is used to array() to make it work with 5.3.
"As of PHP 5.4 you can also use the short array syntax, which replaces array() with []."

changes the [] arrays to array() as it does not work in php 5.3

---

README.md

This config item was not listed in README.md previously. It should be known that by default if you use &lt;pre&gt; tags in your content newlines will get stripped out.

Add previously undocumented config option: setKeepNewLines(false)

---

.github_changelog_generator
CHANGELOG.md

[Full Changelog](https://github.com/caxy/php-htmldiff/compare/v0.1.9...v0.1.10)
In order to be compatible with PHP8 we had to upgrade some vendor packages.
Since these vendor packages have dropped support for older versions of PHP we had todo the same, therefore this version is not compatible anymore with PHP versions prior to 7.3
In case you are not able to upgrade your PHP version, please pin version v0.1.9 of php-htmldiff in your composer config.
- Fixed the keywords that made this version incompatible with PHP8
- Upgraded PHPUnit dependencies with a PHP8 compatible version

Changelog for release v0.1.10

---

README.md
lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php
lib/Caxy/HtmlDiff/Table/TableDiff.php

Not much more to say: I already feed the differ purified HTML for my use case, so I do not another pass. Also, it broke some of my tags (`<figure>` & `<figcaption>` for example).

Added option to disable HTML purifier

---

lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php

While investigating if I could improve the performance for this PR https://github.com/caxy/php-htmldiff/issues/101 I stumbled upon two bottlenecks.
The code was really complex, and hard to comprehend. It was  a huge loop with loads of code-flow inside that was affected by what character was being processed, what character was processed previously, and what process was comming up.
I replace it by mostly regex parsing that does the heavy lifting, speeding this method up by 98%
- Old
- New
While finding blocks we have todo a whitespace check of part of the old sentence, this is done loads of times. This is done by referencing the oldWords array, and temporarily making a string from part of that array, and then checking if that string is only whitespace.
A couple of years ago I already added …

Performance enhancements. Rebuild the word parser and replace the whitespace checker in the match finder.

---

.gitattributes

The size of php-htmldiff on disk is 10MB. This may not sound like much, but that could easily make it the single largest package in any given Composer install. This could be easily reduced to <1MB by simply excluding the demos and tests from packaged releases. Anyone who still wants access to those files would still get them by simply cloning from source, but the thousands of other projects simply using this as a library would save a ton of bandwidth and build time. (literally something like 16TB across the [1.6M installs of this project](https://packagist.org/packages/caxy/php-htmldiff/stats).)
This is an increasingly common pattern for Composer libraries, following the [strategy outlined here](https://madewithlove.be/gitattributes/).

Reduce release size by excluding demos and tests.

---

CHANGELOG.md
README.md
lib/Caxy/HtmlDiff/AbstractDiff.php
lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php

This was adopted from the original library by rashid2538 that this fork is based on. 
The feature tried to wrap the special tags in `<ins class='mod'>` tags. However, this never really worked properly and usually ended up crippling the HTML.
Given the feature never really worked, and I can not think of any use-case for it anyway, I decided to remove it and fix
[Issue 106](https://github.com/caxy/php-htmldiff/issues/106) where it was sometimes impossible to diff HTML that contained these special tags.
This also simplifies the code in `insertTag()`
I understand this chance can be a bit controversial, but I would argue it is for the best, none of the maintainers of this library intentionally added it, and its pretty vague what it is even used for.
In case you have a use-case for this, please …

Remove special-case-tags feature

---

lib/Caxy/HtmlDiff/ListDiffLines.php

`mb_convert_encoding($new, 'HTML-ENTITIES', "UTF-8")` is deprecated in PHP 8.2.

Fix #120: deprecated HTML-ENTITIES encoding

---

lib/Caxy/HtmlDiff/HtmlDiff.php
lib/Caxy/HtmlDiff/HtmlDiffConfig.php
tests/fixtures/HtmlDiff/simple-list.html
tests/fixtures/HtmlDiff/spaces-added.html
tests/fixtures/HtmlDiff/spaces-removed-inside-tag.html

This feature tries to provide a fix for #109. It adds a setting `spaceMatching` which can be set to true so spaces aren't ignored at all.
The HTML provided needs to have the meaningless spaces removed beforehand so only the spaces that we want to compare are present. I think this is more easily done by the developer using the library since it knows more about the HTML being used. The case were I want to apply it is for the code generated by a HTML editor that allows a limited set of tags with predefined layout behavior.
I've added some test cases. I haven't tested the code out of these test cases but I think it will serve my purposes well. I've created the PR so it makies its way while I get to implement it on my project. I might have overlooked something and the naming could probably be …

Add spaceMatching setting that matches all spaces

---

lib/Caxy/HtmlDiff/HtmlDiff.php

This PR fixes some errors in our test pipelines recently with PHP 8.4 and expecting explicit nulllable types.
Would be good to get this merged and released upstream, we are currently using a patch for now.

fix(php 8.4): Add explicit nullable type

---

lib/Caxy/HtmlDiff/Table/TableDiff.php

https://github.com/caxy/php-htmldiff/issues/123

php 8.2: Deprecated function mb_convert_encoding()

---

lib/Caxy/HtmlDiff/AbstractDiff.php
tests/fixtures/HtmlDiff/multiline-tag.html

When using newlines within htmltags the regular expression used doesn't account for newlines, this pull request aims to fix this issue.

Correctly match newlines whitin htmltags.

---

lib/Caxy/HtmlDiff/Table/AbstractTableElement.php
lib/Caxy/HtmlDiff/Table/TableCell.php
lib/Caxy/HtmlDiff/Table/TableDiff.php
lib/Caxy/HtmlDiff/Table/TableRow.php

This PR solves the E_DEPRECATED errors such as:
```
Caxy\\HtmlDiff\\HtmlDiffConfig::setCacheProvider(): Implicitly marking parameter $cacheProvider as nullable is deprecated, the explicit nullable type must be used instead
```
in file caxy/php-htmldiff/lib/Caxy/HtmlDiff/HtmlDiffConfig.php
See also https://www.php.net/manual/en/migration84.deprecated.php
After merging this PR, please make a new release as well, such that users of composer can update easily.

Removed E_DEPRECATED error explicit nullable types

---

lib/Caxy/HtmlDiff/HtmlDiffConfig.php
lib/Caxy/HtmlDiff/LcsService.php
lib/Caxy/HtmlDiff/ListDiffLines.php

I found some more deprecations warnings similar to https://github.com/caxy/php-htmldiff/pull/132

Fix: Removed some more E_DEPRECATED error explicit nullable types
